package com.toy.mapper;

import com.toy.dao.ToyAdmin;
import com.toy.dao.ToyAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToyAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int countByExample(ToyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int deleteByExample(ToyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int insert(ToyAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int insertSelective(ToyAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    List<ToyAdmin> selectByExample(ToyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    ToyAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByExampleSelective(@Param("record") ToyAdmin record, @Param("example") ToyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByExample(@Param("record") ToyAdmin record, @Param("example") ToyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByPrimaryKeySelective(ToyAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_admin
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByPrimaryKey(ToyAdmin record);

    ToyAdmin findByName(String username);
}