package com.toy.mapper;

import com.toy.dao.ToyUser;
import com.toy.dao.ToyUserExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int countByExample(ToyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int deleteByExample(ToyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int insert(ToyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int insertSelective(ToyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    List<ToyUser> selectByExample(ToyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    ToyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByExampleSelective(@Param("record") ToyUser record, @Param("example") ToyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByExample(@Param("record") ToyUser record, @Param("example") ToyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByPrimaryKeySelective(ToyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toy_user
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    int updateByPrimaryKey(ToyUser record);

    List<ToyUser> selectUsers(HashMap<?, ?> hashMap);

    int count(HashMap<?, ?> hashMap);
}