package com.toy.dao;

public class ToyAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_admin.ID
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_admin.username
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_admin.password
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_admin.ID
     *
     * @return the value of toy_admin.ID
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_admin.ID
     *
     * @param id the value for toy_admin.ID
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_admin.username
     *
     * @return the value of toy_admin.username
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_admin.username
     *
     * @param username the value for toy_admin.username
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_admin.password
     *
     * @return the value of toy_admin.password
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_admin.password
     *
     * @param password the value for toy_admin.password
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public ToyAdmin() {

    }
    public ToyAdmin(int id ,String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }
}