package com.toy.dao;

import java.util.Date;

public class ToyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_user.ID
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_user.name
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_user.age
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_user.birthday
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_user.email
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_user.sex
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toy_user.remark
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_user.ID
     *
     * @return the value of toy_user.ID
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_user.ID
     *
     * @param id the value for toy_user.ID
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_user.name
     *
     * @return the value of toy_user.name
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_user.name
     *
     * @param name the value for toy_user.name
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_user.age
     *
     * @return the value of toy_user.age
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_user.age
     *
     * @param age the value for toy_user.age
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_user.birthday
     *
     * @return the value of toy_user.birthday
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_user.birthday
     *
     * @param birthday the value for toy_user.birthday
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_user.email
     *
     * @return the value of toy_user.email
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_user.email
     *
     * @param email the value for toy_user.email
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_user.sex
     *
     * @return the value of toy_user.sex
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_user.sex
     *
     * @param sex the value for toy_user.sex
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toy_user.remark
     *
     * @return the value of toy_user.remark
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toy_user.remark
     *
     * @param remark the value for toy_user.remark
     *
     * @mbggenerated Tue Aug 02 11:49:49 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}